apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: apache
    repoURL: https://charts.bitnami.com/bitnami
    path: .
    targetRevision: 10.5.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
