apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm
    server: https://kubernetes.default.svc
  source:
    repoURL: https://victoria-oa.github.io/rubyappp-helm/
    chart: ruby-web
    targetRevision: 0.1.0
    helm:
      values: |
        replicaCount: 1
        postgres:
          db: mydatabase
          image:
            repository: oluwasanmivic123/docker_db
            tag: latest
            pullPolicy: IfNotPresent
        rubyapp:
          image:
            repository: oluwasanmivic123/docker_web
            tag: latest
            pullPolicy: IfNotPresent
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: argocd-role
rules:
- apiGroups: [""]
  resources: ["applications"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argocd
  name: argocd-role-binding
subjects:
- kind: ServiceAccount
  name: argocd-service-account
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
